name: Build Wheels for All Systems

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install openssl zlib

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.19.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

          CIBW_SKIP: "*-musllinux_* *-win32 *-i686"

          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "arm64"

          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_34_x86_64"

          CIBW_BEFORE_ALL_LINUX: "dnf install -y openssl-devel zlib-devel"

          CIBW_BEFORE_ALL_WINDOWS: "vcpkg install openssl:x64-windows zlib:x64-windows"

          CIBW_ENVIRONMENT_WINDOWS: 'INCLUDE=C:\\vcpkg\\installed\\x64-windows\\include LIB=C:\\vcpkg\\installed\\x64-windows\\lib'

          CIBW_ENVIRONMENT_MACOS: 'MACOSX_DEPLOYMENT_TARGET=15.0 CFLAGS="-I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/zlib/include" LDFLAGS="-L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/zlib/lib"'

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epy-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl